### ISSUE TITLE
 npm run dev  报错

### ISSUE THREAD

**Issue by LessTong** [taylorchen709/vueAdmin#5]
[Vue warn]: Error when rendering component <ElRow>:
Uncaught TypeError: _vm._h is not a function(…)

down 下来代码之后  npm run dev  报错  怎么解决啊

**Comment by taylorchen709** [comment]
Vue 2.1.5 将 _h 重命名为 _c，而 Element 目前发的版本都是用以前的 compiler 编译的，导致新版 runtime 无法运行 Element。目前的解决方案是锁定 Vue 的版本为 2.1.4

重新安装一下版本
"vue-template-compiler": "2.1.4"
"vue-loader": "10.0.0"
"vue": "2.1.4"

具体命令如下：
npm remove vue 
npm remove vue-template-compiler
npm remove vue-loader
npm install vue@2.1.4
npm install vue-template-compiler@2.1.4 
npm install vue-loader@10.0.0

**Comment by wwb568109135** [comment]
good

**Comment by calmking** [comment]
🐂 我的哥

**Comment by calmking** [comment]
我的错误是  Uncaught SyntaxError: Unexpected token import  这个事什么原因啊？谢谢大侠

**Comment by Jsharkc** [comment]
❯ npm run dev

> vueadmin@1.0.5 dev /Users/jsharkc/Documents/Github/vue-admin
> node build/dev-server.js

> Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (/Users/jsharkc/Documents/Github/vue-admin/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/jsharkc/Documents/Github/vue-admin/build/dev-server.js:82:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! vueadmin@1.0.5 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vueadmin@1.0.5 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vueadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vueadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vueadmin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jsharkc/Documents/Github/vue-admin/npm-debug.log
